name: Build Arch

on:
  workflow_dispatch:
  release:
    types: [created]
  schedule:
    - cron: '0 0 * * MON'

# the jobs are based on these notes:
# https://github.com/horsicq/Detect-It-Easy/blob/master/docs/BUILD.md
jobs:
  build-arch:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm qt5-base qt5-script qt5-svg qt5-tools base-devel git
          pacman -S --noconfirm imagemagick

      - name: Create user
        run: |
          useradd builduser -m 
          passwd -d builduser 
          echo 'builduser ALL=(ALL) ALL' | tee -a /etc/sudoers 

      - name: Clone DIE-engine
        run: |
          cd $HOME 
          git clone --recursive https://github.com/horsicq/DIE-engine
          
      - name: Build
        run: |
          sudo chown -R builduser /__w/DIE-engine/DIE-engine
          sudo -u builduser bash -c 'bash -x build_archpkg.sh'
          rm -Rf /__w/DIE-engine/DIE-engine/release/*debug*

      - name: Upload Release as Download
        uses: softprops/action-gh-release@v2
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: |
            /__w/DIE-engine/DIE-engine/release/*.pkg.tar.zst
